/* Generated By:JavaCC: Do not edit this line. PolConstants.java */
public interface PolConstants {

  int EOF = 0;
  int US = 6;
  int SAYI = 7;
  int X = 8;
  int ARTI = 9;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"^2\"",
    "<SAYI>",
    "<X>",
    "\"+\"",
  };

}
