/* Generated By:JavaCC: Do not edit this line. EvalParseConstants.java */
public interface EvalParseConstants {

  int EOF = 0;
  int NUMBER = 3;
  int EOL = 4;
  int BITTI = 5;
  int ASSIGN = 6;
  int YAZDIR = 7;
  int PLUS = 8;
  int MINUS = 9;
  int TIMES = 10;
  int DIVIDE = 11;
  int POWER = 12;
  int EXP = 13;
  int LOG = 14;
  int SQRT = 15;
  int SIN = 16;
  int COS = 17;
  int MAX = 18;
  int MIN = 19;
  int X = 20;
  int ID = 21;
  int COM = 22;
  int LPR = 23;
  int RPR = 24;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\" \"",
    "<NUMBER>",
    "<EOL>",
    "<BITTI>",
    "\"=\"",
    "<YAZDIR>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"exp\"",
    "\"log\"",
    "\"sqrt\"",
    "\"sin\"",
    "\"cos\"",
    "\"max\"",
    "\"min\"",
    "\"x\"",
    "<ID>",
    "\",\"",
    "\"(\"",
    "\")\"",
  };

}
