/* Generated By:JavaCC: Do not edit this line. PolConstants.java */
public interface PolConstants {

  int EOF = 0;
  int BOLME = 6;
  int US = 7;
  int TOPLAM = 8;
  int SAYI = 9;
  int X = 10;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<BOLME>",
    "\"^\"",
    "\"+\"",
    "<SAYI>",
    "<X>",
  };

}
