/* Generated By:JavaCC: Do not edit this line. CalcInputParserConstants.java */
public interface CalcInputParserConstants {

  int EOF = 0;
  int EQ = 1;
  int ADD = 2;
  int SUB = 3;
  int MUL = 4;
  int DIV = 5;
  int DIGIT = 6;
  int DOT = 7;

  String[] tokenImage = {
    "<EOF>",
    "<ADD>",
    "<SUB>",
    "<MUL>",
    "<DIV>",
    "\"=\"",
    "<DIGIT>",
    "<DOT>",
  };

}
