/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
public interface ParserConstants {

  int EOF = 0;
  int SEMI = 1;
  int ASSIGN = 2;
  int PRINT = 3;
  int LPR = 4;
  int RPR = 5;
  int DIGIT = 6;
  int ID = 7;
  int NUM = 8;
  int COMMA = 9;
  int PLUS = 10;
  int MINUS = 11;
  int TIMES = 12;
  int DIVIDE = 13;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\";\"",
    "\":=\"",
    "\"print\"",
    "\"(\"",
    "\")\"",
    "<DIGIT>",
    "<ID>",
    "<NUM>",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<token of kind 14>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
